package com.system.wms.dao;

import com.system.wms.pojo.Administrator;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AdministratorMapper {
    

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table administrator
     *
     * @mbg.generated Sun Dec 23 19:30:19 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table administrator
     *
     * @mbg.generated Sun Dec 23 19:30:19 CST 2018
     */
    int insert(Administrator record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table administrator
     *
     * @mbg.generated Sun Dec 23 19:30:19 CST 2018
     */
    int insertSelective(Administrator record);

    Administrator selectByPrimaryKey(Integer id);

   
    int updateByPrimaryKeySelective(Administrator record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table administrator
     *
     * @mbg.generated Sun Dec 23 19:30:19 CST 2018
     */
    int updateByPrimaryKey(Administrator record);
}